print('Hello World')
print('Whats ur name')
myName = input()
print('It is good to meet you'+myName)
print(len(myName))
print('What is your age?')
age = input()
print('You will be '+ str(int(age)+1) +' in a year')